<<<<<<< HEAD
remote_theme: poole/hyde
=======
theme: minima
#remote_theme: poole/hyde
>>>>>>> 49a0cc12d7ad8ab0f5175ce63b328c5d66fb37d0

# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup

<<<<<<< HEAD
#theme: jekyll-theme-minimal
=======
>>>>>>> 49a0cc12d7ad8ab0f5175ce63b328c5d66fb37d0

title: Ying Li
description: portfolio for data science life cycle


# Setup
tagline:          'hello'
description:      'Data science life cycle projects' 
url:              "http://yingli.github.io"
baseurl:          "/portfolio"


paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/yingli/portfolio
