theme: jekyll-theme-minimal
#remote_theme: daattali/beautiful-jekyll
#remote_theme: mmistakes / minimal-mistakes
markdown: kramdown
title: Ying Li
description: portfolio for data science life cycle

permalink:        pretty

# Setup
tagline:          'hello'
description:      'Data science life cycle projects' 
url:              "http://yingli.github.io"
baseurl:          "/portfolio"


paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/yingli/portfolio
